### ISSUE TITLE
latest grunt-connect-proxy broken

### ISSUE THREAD

**Issue by drmikecrowe** [beeman/loopback-angular-admin#68]
I'm seeing this:

```
Loading "connect_proxy.js" tasks...ERROR
>> TypeError: Cannot read property 'prototype' of undefined
```

Found [this grunt-connect-proxy](https://github.com/drewzboto/grunt-connect-proxy/issues/97) bug.

I resolved by manually:

```
rm -rf node_modules/grunt-connect-proxy
npm install eventemitter3@0.1.6
npm install grunt-connect-proxy
```

**Comment by beeman** [comment]
Thanks for your issue, can you confirm it's fixed in master? :)

**Comment by beeman** [comment]
Please reopen if it's still the same with the latest master :)

**Comment by thomasvs** [comment]
It is not fixed in master.  I ran into this setting up a project on a new machine with npm install.

Please reopen and fix properly.

**Comment by thomasvs** [comment]
(to be clear - it looks this is a bug in grunt-connect-proxy, and 0.2.0 doesn't fix that)

**Comment by beeman** [comment]
Will try to reproduce than fix.

**Comment by drmikecrowe** [comment]
@thomasvs Can you confirm you're using the right version of eventemitter?
```
-> % cat node_modules/eventemitter3/package.json | grep version
  "version": "0.1.6",
```
