### ISSUE TITLE
User information in header lost on screen refresh

### ISSUE THREAD

**Issue by palmerjc** [beeman/loopback-angular-admin#96]
.controller('MainCtrl', function($scope, $rootScope, $state, $location,  CoreService, User, gettextCatalog, AppAuth) {

	AppAuth.ensureHasCurrentUser(function(user)
    {
      $scope.currentUser = user;
	});

Needs to be changed to

  .controller('MainCtrl', function($scope, $rootScope, $state, $location,  CoreService, User, gettextCatalog) {

 $scope.currentUser = User.getCurrent();

**Comment by beeman** [comment]
Thanks @palmerjc!

It looks like it's a regression cause by this commit https://github.com/beeman/loopback-angular-admin/commit/7497639eaf9028988c587dd928214e156313ae06

@dthib could you maybe find time to fix this?

**Comment by josx** [comment]
Make a PR to solve this based on @palmerjc  work.

**Comment by dthib** [comment]
That's exactly what I changed because it was not working with social authentication :)
I guess you are working with normal login?
Best,

**Comment by josx** [comment]
If you dont use social networks still works with this code. 
Try to reload, ones you get logged in.

**Comment by yshing** [comment]
This issue is cause by [/client/app/modules/users/services/appauth.service.js](https://github.com/beeman/loopback-angular-admin/blob/master/client/app/modules/users/services/appauth.service.js#L49-L85)
The **ensureHasCurrentUser** Method
$cookies.access_token is always false.
change all "$cookies.access_token" to "$cookies.accessToken" solves this issue

**Comment by beeman** [comment]
Thanks for the contributions guys.

This should be fixed in master, @palmerjc could you please verify this?

@dthib can you please verify if the social login now works on master too?

**Comment by dthib** [comment]
Thanks for the fix! OK I will check that during the week.
Best,
Thibaut

**Comment by dthib** [comment]
Hi again,
I have tested it and I don't think it's better:
- The social login it's not working anymore since User.getCurrent if still called and undefined is returned for social connexion (any idea of the reason for this behavior?)
- If i put back ensureHasCurrentUser, the connexion is  not working anymore because of the change   access_token to accessToken

If you have any idea...
Best,
Thibaut

**Comment by brainwatch** [comment]
Hi

The problem still persists.

Social logins not working ( using ensureHasCurrentUser() and also User.getCurrent() ) with and without accessToken changes.

My observation is 
1. access token is available as "access_token" only.
2. the http call to "auth/current" from ensureHasCurrentUser is looking for client web server path ( http://localhost:9000/auth/current ) whereas its available at server ( http://localhost:3000/auth/current ). Hence the current user data is not available, hence the page refresh is always redirecting to login page even post login ( And so do the social login redirect ).

Appreciate if there is a quick fix available for this.

Thanks

**Comment by ktersius** [comment]
I think this bug should be fixed by merge https://github.com/beeman/loopback-angular-admin/pull/135.

**Comment by beeman** [comment]
Should be fixed. If not, please reopen the issue with some steps to reproduce. Thanks!
